### ISSUE TITLE
Feature 1: User can create a deck of flashcards

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to create a deck to store flashcards.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When users click on a button an input will appear for the user to choose their deck's name. Once they are chosen the name they can click "Continue" to save the deck.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109567499/200076312-557f7444-d612-4ca9-b57e-c5f54b3010db.png)

![image](https://user-images.githubusercontent.com/109567499/200076356-1aa4e446-4f07-48d0-9fc2-afa4295e3d1b.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Setup `schema.sql` with schema from dbdesigner. **Remember to change name to have "" around both "public" and "tableName" **

### ☁️ Server Tasks

- [x] Set up express service, listen method, and errorMiddleware to catch errors
- [x] Update `server/index.js` to listen for a POST request at location for creating a deck
  - [x] It should require a name, there should be a unique serial ID number, the userId and deckConfidence should be sent as 1 
        for the time being 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to render the home page with a button/a tag that will open the modal
- [x] Create a component to render the modal but with a hidden class
  - [x] Attach an onClick listener to run a function to display a modal
  - [x] The modal should have onChange and onSubmit functions
    - [x] onChange should update a state with the value of what is being typed by the user
    - [x] onSubmit should take the value in the state and send a post request to the server to add the deck
- [x] When the response is received the modal should close.
- [x] There should be an xmark in the corner of the modal to close without submitting a new deck
### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
