### ISSUE TITLE
Feature 10: User can reset their knowledge rating of a deck

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/final-project#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can reset their knowledge rating of a deck

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the options page for a deck there will be an icon for resetting knowledge next to the percentage number. Clicking on this icon will bring up a confirmation screen before an action is taken.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109567499/200080228-50fd49e5-8686-44bc-be5f-040e2bb9b9f0.png)

![image](https://user-images.githubusercontent.com/109567499/200080256-95c47077-694b-405c-bdda-5109a3ed2ed0.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to include a post route to update the flashcards table
  - [x] This should require the deckId and userId
  - [x] It should update all instances where the deckId and userId match and set the confidence to 0
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update options page component to have an icon for resetting the confidence
- [x] Create a component to for the modal to display a reset knowledge
- [x] Update decks.jsx showModal function
  - [x] it should also include the deckName and deckId for the reset
    - [x]  I think we can just rename the const variables to look more reusable and add to the if condition
  - [x] Make sure to pass the deckId and deckName through as props
  
- [x] Go back to the reset knowledge modal
  - [x] Create a similar form to the delete deck modal that displays:
    - [x] deck name
    - [x] a warning message
    - [x] cancel and confirm buttons

- [x] Create a function to reset the knowledge
  - [x] Take the deckId from the props and use that in the req
  - [x] use a fetch request to send the request
  - [x] once the response is received then use the submitModal function to send a new request and update the decks

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
