### ISSUE TITLE
Feature 11: User can create an account

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/final-project#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account. This will hash the password and save the stored information in the database.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user first arrives to the site it will show a sign up page (with the option of signing up). After filling out the form the page will change to the sign in screen.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109567499/200080422-21fc8e06-34e0-4987-a6c1-317a7243de67.png)

![image](https://user-images.githubusercontent.com/109567499/200081265-e1b69d04-3ab0-4847-8abc-bc0f347663b6.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to require argon2
- [x] Set up a new post route that requires a username and a password
- [x] user argon2 to hash the password
- [x] query the database and only return the userId, username, and joinedAt time
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to house the auth form
- [x] For now render this as the home page instead of the decks
- [x] The the form should have an input for username, password (type password so that it is hidden), and a button to submit
- [x] Define change function to update the state with the username and password being typed by the user
- [x] Define a submit function to send a fetch request to the db to create the new user
- [x] Make sure we are receiving the correct information returned from the request

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
