### ISSUE TITLE
Feature 12: User can sign into their account

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/final-project#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign into their account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From the log in page, users will input their username and password to submit a request to log in. A successful request will bring the user to the decks view page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109567499/200080533-e82ab6a0-13fe-4ae0-b4ab-aa0bc7658261.png)

![image](https://user-images.githubusercontent.com/109567499/200081188-5408376c-c47d-464c-843a-c39fe03fd4cb.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to require jsonwebtoken
- [x] Update `server/index.js` to include a POST method for sign in
  - [x] It should require a username and password from the form
  - [x] It should query the database for the userid and hashedPassword where the username matches the provided username
  - [x] Use argon2 to verify the password with the hashedPassword
  - [x] if it is not matching then throw an unspecific client error
  - [x] if it is matching then create a payload and token and send that as a response
  - [x] Test with HTTPie
  - [x] Handle all errors and respond to the client
  - [x] Go to Client Tasks and built / update components before updating the userId portion 

- [x] We need to update all requests that require a userId to actually take the userId
  - [x] We need to pull the token from the request which was sent through the app context and use this instead of userId
  - [x] Test with HTTPie
  - [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update component to the auth form to use conditional logic to determine whether the user is going to sign in or sign up
  - [x] Include some text and an anchor to the other page on the bottom of the form if the user wants to do the other action
  - [x] Modify the sign up request to also be able to handle sign in request
  - [x] Make sure we are getting the correct response (should be a json webtoken) 
    - [x] Once the request is working create a function to for the sign in
      - [x] This should set local storage to store the token and then update the user with the payload user information

- [x] Once the form is working, render the home page again and use conditional logic to send the user to the auth form if they are not logged in

Once this is complete, go back to update the server to user the token instead of the hard coded value

- [x] Set up React Context
  - [x] Create a react context component and import it into app.jsx
  - [x] Use the context provider to have the user and token available in context
  - [x] the context will be passed through the header for requests 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
