### ISSUE TITLE
Feature 13: User can sign out of their account

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/final-project#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign out of their account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the deck view page there will be an option to sign out. Clicking this will log the user out of the account.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109567499/200080847-ca472769-a8b3-4806-a83b-313b56b7cdb5.png)

![image](https://user-images.githubusercontent.com/109567499/200081115-d5c1c105-8e73-4f34-b8e8-a06097f114bf.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update app.jsx to have a function to handle signing out
  - [x] it should remove the user-token from local storage
  - [x] then update the state with the user being null
  - [x] pass this function to header.jsx
- [x] Update header.jsx to have a location for sign out
  - [x] Instead of the figma design, maybe move header title to left side then put sign out on the right side of the header so that it is available on any page?
  - [x] Clicking the sign out should trigger the function that was passed as a prop which signs out the user and should redirect to the sign in screen 
  - [x] Pass user to the header as a prop or use context?
    - [x] Sign Out should only be available if the user is signed in

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
