### ISSUE TITLE
Feature 2: User can add flashcards to a deck

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to add a flashcard (consisting on a question and an answer) to their deck.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user clicks on the folder, an options page for that deck will appear. On the page there will be an option to add a card to the deck which will show the user a new screen with two card faces. The cards will indicate which is for the question and which is for the answer. The user then clicks on save to save the card.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109567499/200403027-045d8954-ca45-4830-a957-0ad6ff9327d7.png)

![image](https://user-images.githubusercontent.com/109567499/200403169-f132575a-7862-46f5-8466-434e06da24be.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to include a get method to return decks based on user (userId 1 for now)
- [x] Update `server/index.js` to include a post method to add flashcards to flashcard table
  - [x] This should require a question body, answer body, and take the body from the state(?) and add userId 1, and confidence 0 for now
  - [x] If not all of them are supplied an error should be returned
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to render folders for each deck
  - [x] Decks should have a page inside with deck name and options
  - [x] Page should have an anchor to trigger a hashChange
- [x] Update main render to attach a hashChange to window on componentDidMount
  - [x] Look to switch into React context over passing functions via props and determining what is necessary in state
  - [x] Based on the hashChange we should conditionally render the "home" page or the "add card" page
    - [x] Clicking the page title should always return to the "home" page
  - [x] Create a simple page to return if page does not exist "Uh oh, sorry page doesn't exist!"
    - [x] Add a link to redirect back to home page "Return to the homepage"
- [x] Add a click event on the folder to display options of the deck
  - [x] If there are multiple decks, clicking on another deck should hide on deck options and only display one option at a time
- [x] Clicked to add card should redirect to the add card page
- [x] Saving card should send a post request to add a card to the db
  - [x] This should be done with a fetch request - make sure to have response and catch methods for the promised return

### 🧑‍⚕️ Clean Up Tasks

**Focus on bolded tasks as they will have the biggest impact/changes in this feature**

- [x] Make sure that no React state objects are being mutated.
- [x] **Make sure that no event listeners are manipulating the DOM directly.**
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] **Confirm that all previous functionality still works without errors.**
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
