### ISSUE TITLE
Feature 14: User can choose how to study their cards

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/final-project#29]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can study their cards in different orders

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When users click to study cards, they will open a modal with different options. The options will change the order that the cards are displayed when studying.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109567499/202552648-c11f8ec8-55b5-460b-a203-842efc961289.png)

![image](https://user-images.githubusercontent.com/109567499/202552922-5096b752-5c2b-44c1-bac5-48bb9a5a697b.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` get route that is used for the study cards
- [x] Use a query param to conditionally return different sql strings
- [x] if there is no query then cards should be returns in cardId order
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a redirect component and implement it (due to setState being asynchronous, href was updating prior to user being set which still redirected users to sign in page after successfully signing in)
- [x] Create a component for the modal that should be a form for studying the deck options
  - [x] It should contain multiple anchor elements for the different options
  - [x] These anchor should pass the deckId and also the type of studying into the route params
- [x] Update home.jsx so that StudyCards also takes a prop for the type of studying
- [x] Update deck.jsx anchor element for study cards to be a button that displays the modal on click
- [x] Update state to have a spot for selecting a study card
- [x] Add the study card display to the renderModalForm prototype method
- [x] Update studycards.jsx fetch method
- [x] it should take the type of studying prop and use that to determine the destination we are fetching from

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
