### ISSUE TITLE
Feature 3: User can view sets of flashcards

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their deck of flashcards

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can click on a deck to display options. When the options page is displayed there they can click the "View Cards" option to see all of the cards in the deck.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109567499/200077223-04019d73-8aa3-4415-92ec-d62fa1ee578a.png)

![image](https://user-images.githubusercontent.com/109567499/200077261-b437d7d1-989a-4703-88a0-7c686cde8471.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to include a method to return a set of cards from a deck
  - [x]  It needs to have a deckId and a userId (set userId to 1 for time being)
  - [x] It should return all cards where the deckId matches the deckId provided at the request time
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to render cards in a deck
  - [x] For now set up a short array with two sets of questions and answers to see how it renders multiple cards
  - [x] The deck name should be displayed at the top
  - [x] The cards should be below the deck name
  - [x] To the right of the deck name there should be an anchor tag linking to add another card to the deck
- [x] create a fetch request to pull the deckId from the currently viewed deck and use that to send the request
  - [x] The return should be the array of objects being the flashcards
  - [x] Pass the return as props to cards component to render the cards 
- [x] Update save new card component to land on deck view screen

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
