### ISSUE TITLE
Feature 15: New Users can follow a tour

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/final-project#31]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can follow a short tour of the app

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After a user registers, the first time they sign into the app they will be offered a walk through of how to use the app

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109567499/202788645-fa332a46-cc5e-49ec-8012-94939330cca6.png)

![image](https://user-images.githubusercontent.com/109567499/202788569-e97326dd-c839-429f-9e87-5f221b2333c7.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to include a column for "newUser" which defaults to true

### ☁️ Server Tasks

- [x] Update `server/index.js` to include a patch route to update the newUser column
- [x] It should take a userId
- [x] it will update the user that matches the userId to have a newUser value of false
- [x] When a user signs in, update the post route to also return the newUser column
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to display the tour (lets say tour.jsx for now)
- [x] Update home.jsx to check if the user in context is a newUser or not
  - [x] if yes it should return the tour
- [x] Update app.jsx to have a function that sends a fetch request to update the user's newUser status to false then when a response is received it takes a shallow copy of the user object, updates the newUser property to false, then updates the state
- [x] tour.jsx should have a counter (in state) to determine which part to show
- [x] The first page should give the user the option to skip the tour which should run the close tour function from app.jsx
- [x] If the user clicks yes
  - [x] there should be a function that increments what page we are on and adds an event listener to the window that listens for clicks to increment the counter
    - [x] can we conditionally remove the eventListener inside of itself if we are on the last page in this function?
- [x] Conditionally render each page based on the position
- [x] I think maybe have a directory for tour pages and then makes each page its own component?
- [x] Use the same type of rendering that the modal uses where tour.jsx has all of the components but conditionally shows each one based on the state counter
- [x] The last page should have a clickable button that runs the close tour function from app.jsx

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
