### ISSUE TITLE
Design Update: Pointer stick in tour 768px and 1280px

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/final-project#35]
## ⚙️ Feature

> ##### Which feature is affected by this update?

User can take a tour of the app

## 📐 Plan

> ##### Summary of the technical approach to be taken.

CSS transforms need to be adjusted for the positioning of the pointer stick.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Run through the tour page by page for both 768px and 1280px (one at a time)
  - [x] On each page check the positioning of the stick
  - [x] Adjust transform positioning so that stick will be displayed "comfortably" in image's paw
- **Clean Up**
  - [x] Remove all buttons and placeholders that don't do anything.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
