### ISSUE TITLE
Bug: App crashing when no content is sent in a request

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/final-project#36]
#### Desired Behavior

> ##### The app should ...

not send a request if the content is empty

#### Actual Behavior

> ##### The app does this instead ...

Display a message to the user that the content is required (deck name, question, answer. . . )

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

Open the new deck modal or create a new card

Submit the deck or new card with no content (no deck name, question, or answer)

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] Update submit handler functions to have a condition clause
- [x] It should check to make sure that the content is not empty
- [x] if it is empty, a message should be displayed to the user saying that content is required
- [x] if it is not empty, the submit function should run properly
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
