### ISSUE TITLE
Feature 4 : User can edit flashcards

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to edit the question or answer content of a card.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

There will be an "Edit Card" clickable icon below each card in a deck. Click this will bring the to a page with the question and answer already populated and saving the card will update the card in the deck.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109567499/200077527-e072faea-2fab-402e-9d46-e47c5c454e29.png)

![image](https://user-images.githubusercontent.com/109567499/200077475-85c6a85b-f8af-480e-9fc7-354926c9d809.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to have a unique card number for each flashcard

### ☁️ Server Tasks

- [x] Update `server/index.js` to have a route to respond to a new GET request
  - [x] This get request should require a card number and userId
- [x] Update `server/index.js` to have a route to respond to PATCH requests
  - [x] It should require a question, answer, userId, and card number
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update renderContent prototype method to have another route to render the EditCards
- [x] Update the key for each item to the card number and give each card an id attribute with the card number to use as reference
- [x] Update the ViewCards page to also render an anchor tag that will link to the edit-cards view
  - [x] The edit cards link should include the cardId
- [x] Create a component to render the edit card view
- [x] Test that the link works by returning a Hello World div
  - [x] This should function similarly to the add cards view but already have predetermined information
  - [x] It should display the deck's name
  - [x] it should have a link that redirects to add a card to the deck from this page
  - [x] On componentDidMount there should be a fetch request that
    - [x] Pulls the question information
    - [x] Updates the state with the question content, answer content, and cardid number
    - [x] Renders the question and answer content to the forms
  - [x] Add an prototype method to update the state with any changes to the question or answer
  - [x] Add a prototype method to handle the submitting of the form
    - [x] it should prevent default
    - [x] send a patch request to the database to update the card information
    - [x] redirect back to the card view page

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
