### ISSUE TITLE
Feature 5: User can delete a flashcard

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a flashcard from a deck

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When users are in the edit card view they can click on an option to Delete Card. This will bring up a confirmation screen before the user can delete the card.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

![image](https://user-images.githubusercontent.com/109567499/200079174-530977bd-759b-4eb9-91c7-ddb760928714.png)

![image](https://user-images.githubusercontent.com/109567499/200079133-ede19362-4dde-4126-a978-587fe90895ed.png)

![image](https://user-images.githubusercontent.com/109567499/200079152-81232395-db75-4da1-9fc8-2f1fd788c322.png)

### ☁️ Server Tasks

- [x] Update `server/index.js` to include a route for a delete method
  - [x] This method should require a card id, and a userId (set to 1 for the time being)
  - [x] **MAKE SURE WHEN WRITING THE METHOD TO INCLUDE WHERE OR ELSE YOU WILL DELETE EVERYTHING** 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update component to the EditCard page to include a button (click type button) that can open the modal
  - [x] showModal and closeModal may need to be passed as props into the EditCard react element
- [x] Modify the current modal form to be a new form component and create a new form component for deleting a card
- [x] Update the showModal and closeModal prototype methods
  - [x] any clickable element should have a unique id
  - [x] showModal should set the state to show (for modal) and a new property with the id of what was clicked
  - [x] This should then be used to determine what type of view to provide on the modal
  - [x] This can happen in a new prototype method like renderModalForm and then pass the form as a child of the modal
- [x] If the submit is clicked on the delete modal is should remove the card
  - [x] it needs to send a fetch request to the db
  - [x] it needs to send a cardId and userId
  - [x] once complete it should redirect the user back to the deck view

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
