### ISSUE TITLE
Feature 7: User can review a deck of flashcards

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can click on an option to study flash cards. It will then show a question and clicking the card will reveal the answer.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can click on an option to study flash cards. It will then show a question and clicking the card will reveal the answer.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109567499/200079326-07d6ba6c-8cbb-406e-bacf-2a1acc0602a1.png)

![image](https://user-images.githubusercontent.com/109567499/200079356-243a3753-06db-46ad-a97f-ab17dce2a8e8.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` /api/cards/:deckId get request to join the decks table using deckId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to render a study card page. . . currently just get the page to display a Hello World! div
- [x] Update deck option page component to display an option to study a deck
  - [x] This should be an anchor tag with an icon
  - [x] The hash should redirect to a link for study cards with the deckId number
- [x] Update app.js to have an additional route that will render the study card page if the hash is the same as the redirected one just reacted
  - [x] Check to make sure this renders the Hello World Div
  - [x] set the initial start to have an empty array for cards and a position of 0
  - [x] when the component mounts send a fetch request to the server for the cards with the matching deck id
    - [x] when the fetch requests finish it should update the state with the cards array
  - [x] make sure a card is displayed with the question content of the card in the current position
    - [x] the backside should be hidden by transforming the card to face backwards and both cards should hide the backside
  - [x] create a prototype function flips the card ( add another state and use that update to rerender with the class?)
  - [x] create a prototype function that goes to the next card
    - [x] it should set a variable equal to the position state increased by one
    - [x] we should check if the new variable is greater than the length of the cards array
      - [x] if yes we should redirect back to the cards view
      - [x] if no we should update state with the new position and change the state for the facing of the card

- [x] Now that I did the work of updating the request route. . .
  - [x] Update any places where this request and deckName are being used so that it does not need to be passed in the hash params as much
- [x] For now leave the modal alone

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
