### ISSUE TITLE
Feature 6: User can delete a deck of flashcards

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can delete an entire set of flashcards from the deck view.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the options view page for a deck there will be an additional option to Delete Deck. Clicking this will bring up a confirmation screen to ensure the user wants to delete the deck.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109567499/200079687-e15ea7a5-a824-4fc7-a423-2392f0d175a2.png)

![image](https://user-images.githubusercontent.com/109567499/200079650-4c2b8549-2325-4c70-b61b-03a0db668143.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to include another delete route to delete an entire desk
  - [x] Check to make sure the deckId is a positive integer
  - [x] Create sql code that deletes all CARDS from flashcards that matches the deckId and userId (1 for now)
    - [x] Then delete all decks from decks that match the deck Id (1 for now)
  - [x] Query the database to delete the cards
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to render a delete deck option in the modal
  - [x] It should display a confirmation message, the deckName, and two options - Cancel and Confirm
  - [x] include a warning to users that all of their cards will be delete
- [x] Update option page component in decks to have an option to delete a deck
  - [x] it should have a unique id for delete deck
- [x] Update the renderModalForm prototype method to also check for the state's form value to be equal to the delete deck id
- [x] Make sure the new content pops up when the delete deck option is clicked
- [x] Now go back and update the delete deck component
  - [x] The cancel on click should close the modal
    - [x] Pass closeModal as a prop and then call it onClick
    - [x] Update the closeModal prototype method
      - [x] Change the if statement logic so that it will send a new fetch request after the delete happens
      - [x] Either conditionally add to check if the state form value is equal to the delete deck id or check the route path?
  - [x] The Confirm on click should delete the deck and then close the modal (the closing modal should trigger a rerender)
    - [x] sends a fetch request to the delete route
    - [x] closes the modal
    - [x] make sure the delete goes through in pgweb

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
