### ISSUE TITLE
Feature 8: User can rate their flashcards

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can score their knowledge 1 - 5 after revealing an answer.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When studying flashcards, there will be 5 options (1 - 5) for the user to rate their "confidence" in that card. Click the score will set the confidence and then go on to the next card.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109567499/200079834-bbe957fe-4772-49b7-a1dc-c78bfa593502.png)

![image](https://user-images.githubusercontent.com/109567499/200079872-aa89ecd4-d519-4c69-88ea-d9476b8431e8.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js`  to have a patch route that requires a cardId, number value (1 - 5), and userId (set to 1 for now)
  - [x] This route should ONLY update the value of the confidence with the number value provided at the card that matches with the cardId and userId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update cardstudy.jsx to include five buttons
- [x] Put them in a flex container, each taking up a fifth of the container spread out equally from each other
  - [x] they should be shaped like circles with a number inside
  - [x] each should have an id number of 1 - 5
  - [x] they should only be visible when the answer is displayed
    - [x] use the reveal state to determine this, if it is on answer then show the icons / icon container
  - [x] when the user clicks one of the icons it should send a fetch request to update the database
    - [x] see if we can just use the event.target.id (maybe assign to variable for clarity) as the req body instead of sending entire state
    - [x] once the response has been received, the card should begin to flip to the front side again
    - [x] make sure the finishFlip onTransition end event is still working properly
      - [x] once cards are finished we can still go to the view cards page
    - [x] make sure that answer is not updating before the card backside is hidden from the user's view

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
