### ISSUE TITLE
Feature 9: User can see their knowledge rating of a deck

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/final-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see their knowledge rating of a deck

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the options page for a deck there will be a meter showing how confident the user is on the deck and then the number in a percentage next to the meter.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/109567499/200080054-52293e18-7cae-485a-b314-f2491ac4b4e0.png)

![image](https://user-images.githubusercontent.com/109567499/200080011-87092151-796f-4716-a06d-9ecd970be968.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` get('/api/decks') route to use aggregate functions
  - [x] This should join the flashcards to the decks table using deckId
  - [x] Use an aggregate to count the number of cards
  - [x] Use an aggregate to sum amount of confidence of all the cards in the deck
  - [x] return these two along with the rest of the deck information
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update options paper component to have a meter and a number at the bottom of the option paper
  - [x] The number should be calculated from the new data we get from the aggregate
    - [x] We should use confidence total / number cards * 5 and multiply it by 100 to get a % out of 100 (may need to take math floor)
    - [x] The meter should have a max of 100 and a fill (attributes)
      - [x] The fill will be the same number being used as the %
      - [x] Use low as 57, high as 78, and optimum is 100

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
